# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Kundaje Lab Official Blog
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Our research focusses on development of statistical and machine learning methods for integrative analysis of diverse functional genomic and genetic data to learn models of gene regulation. We have led the analysis efforts of the Encyclopedia of DNA Elements (ENCODE) and The Roadmap Epigenomics Projects with the development of novel methods for
list:@
    :Denoising and normalization of large-scale functional genomic data
    : Dissecting combinatorial transcription factor co-occupancy within and across cell-types
    : Predicting cell-type specific enhancers from chromatin state profiles
    : Modeling 3D genome architecture and predicting cell-type specific enhancer-promoter interactions
    : Learning transcriptional regulatory networks that integrate proximal and distal cis and trans signals.
    :Improving the detection and interpretation of potentially causal disease-associated variants from genome-wide association studies
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: anshulkundaje
github_username:  kundajelab

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
