# Setup
title:        Kundaje Lab Official Blog
tagline:      Clever tagline here 
baseurl:      "/kundajelab.github.io"

paginate:     1

# About/contact
author:
  name:      Kundaje Lab
   url:      https://github.com/kundajelab

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

# include subdirectories
#keep_files: ["_site/html/"]